INSERT INTO book VALUES(DEFAULT,'プログラミング言語C',current_timestamp),
INSERT INTO book VALUES(DEFAULT,'やさしいコンピューター科学',current_timestamp),
INSERT INTO book VALUES(DEFAULT,'ゲーデル、エッシャー、バッハ―あるいは不思議の環',current_timestamp),
INSERT INTO book VALUES(DEFAULT,'TeXブックコンピュータによる組版システム',current_timestamp),
INSERT INTO book VALUES(DEFAULT,'人月の神話狼人間を撃つ銀の弾はない',current_timestamp),
